################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJDUMP_LIST := 
C_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
AppLibraries/DS3231 \
AppLibraries/ESP32_API \
AppLibraries/FT6236 \
AppLibraries/GateWay_API \
AppLibraries/LORA \
AppLibraries/LoRa_API \
AppLibraries/SPIFLASH \
AppLibraries/TFT16BIT \
AppLibraries/User_Interface \
AppLibraries/lvgl/demos/benchmark/assets \
AppLibraries/lvgl/demos/benchmark \
AppLibraries/lvgl/demos/keypad_encoder \
AppLibraries/lvgl/demos/music/assets \
AppLibraries/lvgl/demos/music \
AppLibraries/lvgl/demos/stress \
AppLibraries/lvgl/demos/widgets/assets \
AppLibraries/lvgl/demos/widgets \
AppLibraries/lvgl/env_support/rt-thread \
AppLibraries/lvgl/examples/anim \
AppLibraries/lvgl/examples/assets \
AppLibraries/lvgl/examples/assets/emoji \
AppLibraries/lvgl/examples/event \
AppLibraries/lvgl/examples/get_started \
AppLibraries/lvgl/examples/layouts/flex \
AppLibraries/lvgl/examples/layouts/grid \
AppLibraries/lvgl/examples/libs/bmp \
AppLibraries/lvgl/examples/libs/ffmpeg \
AppLibraries/lvgl/examples/libs/freetype \
AppLibraries/lvgl/examples/libs/gif \
AppLibraries/lvgl/examples/libs/png \
AppLibraries/lvgl/examples/libs/qrcode \
AppLibraries/lvgl/examples/libs/rlottie \
AppLibraries/lvgl/examples/libs/sjpg \
AppLibraries/lvgl/examples/others/fragment \
AppLibraries/lvgl/examples/others/gridnav \
AppLibraries/lvgl/examples/others/imgfont \
AppLibraries/lvgl/examples/others/monkey \
AppLibraries/lvgl/examples/others/msg \
AppLibraries/lvgl/examples/others/snapshot \
AppLibraries/lvgl/examples/porting \
AppLibraries/lvgl/examples/scroll \
AppLibraries/lvgl/examples/styles \
AppLibraries/lvgl/examples/widgets/animimg \
AppLibraries/lvgl/examples/widgets/arc \
AppLibraries/lvgl/examples/widgets/bar \
AppLibraries/lvgl/examples/widgets/btn \
AppLibraries/lvgl/examples/widgets/btnmatrix \
AppLibraries/lvgl/examples/widgets/calendar \
AppLibraries/lvgl/examples/widgets/canvas \
AppLibraries/lvgl/examples/widgets/chart \
AppLibraries/lvgl/examples/widgets/checkbox \
AppLibraries/lvgl/examples/widgets/colorwheel \
AppLibraries/lvgl/examples/widgets/dropdown \
AppLibraries/lvgl/examples/widgets/img \
AppLibraries/lvgl/examples/widgets/imgbtn \
AppLibraries/lvgl/examples/widgets/keyboard \
AppLibraries/lvgl/examples/widgets/label \
AppLibraries/lvgl/examples/widgets/led \
AppLibraries/lvgl/examples/widgets/line \
AppLibraries/lvgl/examples/widgets/list \
AppLibraries/lvgl/examples/widgets/menu \
AppLibraries/lvgl/examples/widgets/meter \
AppLibraries/lvgl/examples/widgets/msgbox \
AppLibraries/lvgl/examples/widgets/obj \
AppLibraries/lvgl/examples/widgets/roller \
AppLibraries/lvgl/examples/widgets/slider \
AppLibraries/lvgl/examples/widgets/span \
AppLibraries/lvgl/examples/widgets/spinbox \
AppLibraries/lvgl/examples/widgets/spinner \
AppLibraries/lvgl/examples/widgets/switch \
AppLibraries/lvgl/examples/widgets/table \
AppLibraries/lvgl/examples/widgets/tabview \
AppLibraries/lvgl/examples/widgets/textarea \
AppLibraries/lvgl/examples/widgets/tileview \
AppLibraries/lvgl/examples/widgets/win \
AppLibraries/lvgl/src/core \
AppLibraries/lvgl/src/draw/arm2d \
AppLibraries/lvgl/src/draw \
AppLibraries/lvgl/src/draw/nxp \
AppLibraries/lvgl/src/draw/nxp/pxp \
AppLibraries/lvgl/src/draw/nxp/vglite \
AppLibraries/lvgl/src/draw/sdl \
AppLibraries/lvgl/src/draw/stm32_dma2d \
AppLibraries/lvgl/src/draw/sw \
AppLibraries/lvgl/src/draw/swm341_dma2d \
AppLibraries/lvgl/src/extra/layouts/flex \
AppLibraries/lvgl/src/extra/layouts/grid \
AppLibraries/lvgl/src/extra/libs/bmp \
AppLibraries/lvgl/src/extra/libs/ffmpeg \
AppLibraries/lvgl/src/extra/libs/freetype \
AppLibraries/lvgl/src/extra/libs/fsdrv \
AppLibraries/lvgl/src/extra/libs/gif \
AppLibraries/lvgl/src/extra/libs/png \
AppLibraries/lvgl/src/extra/libs/qrcode \
AppLibraries/lvgl/src/extra/libs/rlottie \
AppLibraries/lvgl/src/extra/libs/sjpg \
AppLibraries/lvgl/src/extra \
AppLibraries/lvgl/src/extra/others/fragment \
AppLibraries/lvgl/src/extra/others/gridnav \
AppLibraries/lvgl/src/extra/others/imgfont \
AppLibraries/lvgl/src/extra/others/monkey \
AppLibraries/lvgl/src/extra/others/msg \
AppLibraries/lvgl/src/extra/others/snapshot \
AppLibraries/lvgl/src/extra/themes/basic \
AppLibraries/lvgl/src/extra/themes/default \
AppLibraries/lvgl/src/extra/themes/mono \
AppLibraries/lvgl/src/extra/widgets/animimg \
AppLibraries/lvgl/src/extra/widgets/calendar \
AppLibraries/lvgl/src/extra/widgets/chart \
AppLibraries/lvgl/src/extra/widgets/colorwheel \
AppLibraries/lvgl/src/extra/widgets/imgbtn \
AppLibraries/lvgl/src/extra/widgets/keyboard \
AppLibraries/lvgl/src/extra/widgets/led \
AppLibraries/lvgl/src/extra/widgets/list \
AppLibraries/lvgl/src/extra/widgets/menu \
AppLibraries/lvgl/src/extra/widgets/meter \
AppLibraries/lvgl/src/extra/widgets/msgbox \
AppLibraries/lvgl/src/extra/widgets/span \
AppLibraries/lvgl/src/extra/widgets/spinbox \
AppLibraries/lvgl/src/extra/widgets/spinner \
AppLibraries/lvgl/src/extra/widgets/tabview \
AppLibraries/lvgl/src/extra/widgets/tileview \
AppLibraries/lvgl/src/extra/widgets/win \
AppLibraries/lvgl/src/font \
AppLibraries/lvgl/src/hal \
AppLibraries/lvgl/src/misc \
AppLibraries/lvgl/src/widgets \
AppLibraries/lvgl/tests/makefile \
AppLibraries/lvgl/tests/src \
AppLibraries/lvgl/tests/src/test_cases \
AppLibraries/lvgl/tests/src/test_fonts \
AppLibraries/lvgl/tests/unity \
Drivers/Devices \
PeriphLibraries/DMA_F4xx \
PeriphLibraries/GPIO_F4xx \
PeriphLibraries/I2C_F4xx \
PeriphLibraries/IT_F4xx \
PeriphLibraries/PERIPH_STATUS \
PeriphLibraries/RCC_F4xx \
PeriphLibraries/SDMMC_F4xx \
PeriphLibraries/STM_LOG \
PeriphLibraries/SYSTEM_F4xx \
PeriphLibraries/TIM_F4xx \
PeriphLibraries/USART_F4xx \
Src/Config \
Src \
Startup \

